import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { loadNnModel, nnArtifactSchema } from "../../src/nn/artifact.ts";
import { nnForwardProbs } from "../../src/nn/transformer.ts";

/**
 * THE fidelity gate for the pure-TS transformer port (backtest-report ethos:
 * "Max's predictor" output is only trustworthy while this is green). The
 * committed artifact carries golden vectors generated by the ORIGINAL PyTorch
 * model (setlist-predictor export_web.py); this replays them through the TS
 * forward pass and asserts the last-position distributions match within 1e-4
 * — far above fp32 rounding, far below any real architectural mismatch.
 */

const ARTIFACT_PATH = fileURLToPath(
  new URL("../../../../data/nn/setlist-transformer.json", import.meta.url),
);
const TOLERANCE = 1e-4;

const raw: unknown = JSON.parse(readFileSync(ARTIFACT_PATH, "utf8"));
const artifact = nnArtifactSchema.parse(raw);
const model = loadNnModel(raw);

describe("nn artifact", () => {
  it("parses, decodes, and carries golden vectors", () => {
    expect(model).not.toBeNull();
    expect(artifact.golden.length).toBeGreaterThanOrEqual(3);
    expect(model?.tokenBySongId.size).toBeGreaterThan(150); // 168 song tokens minus context-only names
  });
});

describe("TS forward pass matches PyTorch golden vectors", () => {
  for (const [caseIndex, golden] of artifact.golden.entries()) {
    it(`case ${caseIndex} (${golden.tokens.length} tokens)`, () => {
      if (!model) throw new Error("model failed to load");
      const probs = nnForwardProbs(model, golden.tokens);

      if (golden.expectedFull) {
        expect(golden.expectedFull).toHaveLength(probs.length);
        let maxDiff = 0;
        for (let v = 0; v < probs.length; v++) {
          maxDiff = Math.max(maxDiff, Math.abs(probs[v] - golden.expectedFull[v]));
        }
        expect(maxDiff).toBeLessThan(TOLERANCE);
      }

      if (golden.expectedTop) {
        for (const { id, prob } of golden.expectedTop) {
          expect(Math.abs(probs[id] - prob)).toBeLessThan(TOLERANCE);
        }
        // The argmax must agree — rank-1 is what an orb leads with.
        let argmax = 0;
        for (let v = 1; v < probs.length; v++) if (probs[v] > probs[argmax]) argmax = v;
        expect(argmax).toBe(golden.expectedTop[0].id);
      }
    });
  }
});
